### ISSUE TITLE
Add multisig support to the stellar client

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscaleX_libs#107]
In a nutshell:
- Set the required number of signatures
- Add/remove signers
- Show the signing options
- Sign a passed(xdr) transaction envelope

**Comment by DylanVerstraete** [comment]
Work in progress:

https://github.com/threefoldtech/jumpscaleX_libs/pull/108

What is in there:

`set_signature_count`: sets the signers and signature count
`create_multisig_transaction`: creates a ms tx and returns transaction xdr in order to be signed by other signers
`sign_multisig_transaction`: signs a transaction xdr and tries to submit it to horizon

I can't seem to find a way to remove a singer

**Comment by robvanmieghem** [comment]
>I can't seem to find a way to remove a singer

Set it's weight to `0`
